// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.


export const citys: String[] = ['TestStadt', 'zweite TestStadt'];

export const cities: String [] = ['Berlin',
    'Hamburg',
    'München',
    'Köln',
    'Frankfurt am Main',
    'Stuttgart',
    'Düsseldorf',
    'Dortmund',
    'Essen',
    'Bremen',
    'Dresden',
    'Leipzig',
    'Hannover',
    'Nürnberg',
    'Duisburg',
    'Bochum',
    'Wuppertal',
    'Bonn',
    'Bielefeld',
    'Mannheim',
    'Karlsruhe',
    'Münster',
    'Wiesbaden',
    'Augsburg',
    'Aachen',
    'Mönchengladbach',
    'Gelsenkirchen',
    'Braunschweig',
    'Chemnitz',
    'Kiel',
    'Krefeld',
    'Halle (Saale)',
    'Magdeburg',
    'Freiburg im Breisgau',
    'Oberhausen',
    'Lübeck',
    'Erfurt',
    'Rostock',
    'Mainz',
    'Kassel',
    'Hagen',
    'Hamm',
    'Saarbrücken',
    'Mülheim an der Ruhr',
    'Herne',
    'Ludwigshafen am Rhein',
    'Osnabrück',
    'Oldenburg',
    'Leverkusen',
    'Solingen',
    'Potsdam',
    'Neuss',
    'Heidelberg',
    'Paderborn',
    'Darmstadt',
    'Regensburg',
    'Würzburg',
    'Ingolstadt',
    'Heilbronn',
    'Ulm',
    'Wolfsburg',
    'Göttingen',
    'Offenbach am Main',
    'Pforzheim',
    'Recklinghausen',
    'Bottrop',
    'Fürth',
    'Bremerhaven',
    'Reutlingen',
    'Remscheid',
    'Koblenz',
    'Bergisch Gladbach',
    'Erlangen',
    'Moers',
    'Trier',
    'Jena',
    'Siegen',
    'Hildesheim',
    'Salzgitter',
    'Cottbus'];