name: Docker image release

on:
  push:
    tags:        
      - v*

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        ref: master      
    - name: Push new docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: troeger/culturestreams
        tags: latest
    - name: Prepare kubectl installation
      run: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -; echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
    - name: Prepare APT
      run: sudo apt update
    - name: Install Kubectl
      run: sudo apt install -y kubectl
    - name: Restart pod for the web app
      run: kubectl delete pod -l app=culturestreams
